package: ycom
version: '4.2.0-dev'
author: Yakamara Media GmbH & Co. KG
supportpage: https://github.com/yakamara/redaxo_ycom/

page:
    title: 'translate:ycom_navi_title'
    perm: admin[]
    block: ycom
    icon: rex-icon fa-group
    subpages:
        docs:
            title: 'translate:ycom_docs'
            perm: admin[]
            pjax: false
            itemclass: pull-right
            icon: rex-icon fa-info-circle
        log:
            title: 'translate:ycom_log'
            perm: admin[]
            itemclass: pull-right

pages:
    system/log/ycom_user:
        title: translate:ycom_user_log
        perm: admin

requires:
    php: '>=7.4'
    packages:
        yform: '>=4.0.4'
        yrewrite: '>=2.6'
    redaxo: '^5.14.2'

system_plugins:
    - auth
    - group
